name: artifact_testing

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to search for the artifact'
        default: 'tarantool/tarantool'
        required: false
      workflow:
        description: 'Workflow to search for the artifact'
        default: 'build_tarantool_pkg.yml'
        required: false
      sha:
        description: 'Commit SHA to search for the artifact'
        default: master
        required: true
      artifact:
        description: 'Name of the artifact'
        default: 'ubuntu-focal'
        required: false

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the module
        uses: actions/checkout@v2
        with:
          # Fetch the entire history for all branches and tags. It is needed for
          # upgrade testing.
          fetch-depth: 0
          # Enable recursive submodules checkout as test-run git module is used
          # for running tests.
          submodules: recursive
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repo: ${{ github.event.inputs.repository }}
          workflow: ${{ github.event.inputs.workflow }}
          commit: ${{ github.event.inputs.sha }}
          name: ${{ github.event.inputs.artifact }}
          workflow_conclusion: success
      - name: Install tarantool
        run: sudo dpkg -i tarantool*.deb
      - name: Install test requirements
        run: pip3 install --user -r test-run/requirements.txt
      - run: cmake .
      - run: make test
