name: tarantool_testing

on:
  repository_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          repo: ${{github.event.client_payload.repository}}
          workflow: ${{github.event.client_payload.workflow}}
          workflow_conclusion: success
          commit: ${{github.event.client_payload.sha}}
          name: ubuntu-focal

      - name: Clone the module
        uses: actions/checkout@v2
        with:
          # Fetch the entire history for all branches and tags. It is needed for
          # upgrade testing.
          fetch-depth: 0
          # Enable recursive submodules checkout as test-run git module is used
          # for running tests.
          submodules: recursive

      - name: Install test requirements
        run: pip3 install --user -r test-run/requirements.txt

      - run: cmake .
      - run: make test
